name: Build Subtitles

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'README.md'

env:
      PYTHONUNBUFFERED: "1"
      WINEDEBUG: "-all"

jobs:
  Build-CI-Versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wine64
          pip install --user git+https://github.com/FichteForks/Myaamori-Aegisub-Scripts.git@pr/fix-style-deduplication#subdirectory=scripts/sub-digest
          pip install requests
          winecfg
      - name: Download Aegisub-cli
        run: |
          wget https://github.com/scrpr/aegisub-cli/releases/download/disable_unique_path/aegisub-cli.zip
          unzip -q aegisub-cli.zip -d aegisub-cli/
      - name: Install custom fonts
        run: |
          wget https://github.com/Kitauji-Sub/subs-shikanoko/releases/download/typeface/fonts.zip
          unzip -q fonts.zip -d Fonts/
          sudo mv Fonts/* /usr/share/fonts/
          fc-cache -fv
      - name: Build substitles
        run: |
          python build_scripts/build.py
      - name: Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        id: semver
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "feat:"
          bump_each_commit: true
      - name: Pack files
        run: |
          zip -r -j sino_subs_${{steps.semver.outputs.version}}.zip build/output/*
      - name: Publish
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: ${{steps.semver.outputs.version_tag}}
          fail_on_unmatched_files: true
          prerelease: false
          draft: false
          generate_release_notes: false
          name: ${{steps.semver.outputs.version}}
          files: |
            sino_subs_*.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sino_subs_built
          path: sino_subs_*.zip